create table public.products (
  id bigint generated by default as identity not null,
  product_code text not null,
  product_name text not null,
  category_id bigint null,
  unit text null,
  price numeric(12, 2) null,
  shelf_life_days integer null,
  barcode text null,
  description text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint products_pkey primary key (id),
  constraint products_barcode_key unique (barcode),
  constraint products_product_code_key unique (product_code),
  constraint products_price_nonnegative check (price is null or price >= 0),
  constraint products_category_id_fkey foreign KEY (category_id) references categories (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_products_category_id on public.products using btree (category_id) TABLESPACE pg_default;

create index IF not exists idx_products_product_name on public.products using btree (product_name) TABLESPACE pg_default;

create trigger trg_products_updated_at BEFORE
update on products for EACH row
execute FUNCTION set_updated_at ();
